#### Question 1

Disply the following sentence in bold font face <br>
"This is fisrt lab of Applied Computational Statics"

In [2]:
start = "\033[1m"
end = "\033[0;0m"

print(start + "This is fisrt lab of Applied Computational Statics" + end)

This is fisrt lab of Applied Computational Statics


#### Question 2

Recreate the following bullet points in  Jupyter notebook markdown cell:
markdown cell : markdown <br>
code cell: Python code <br>
Subject: Statistics 

markdown cell : markdown <br>
code cell: Python code <br>
Subject: Statistics 

#### Question 3

**Run the following code in two different Jupyter notebook cells. Run one cell as a code cell. Run the other cell as a Markdown cell. Why is the output different?**

#### Question 4

**Use *float()* to create a number from a string like '12.34'. Make sure the result is really a number!**

In [4]:
a = float("12.54")
type(a)

float

#### Question 5

Write a simple Python program that displays the following **powers of 2**, one per line: $$2^1, 2^2, 2^3, 2^4, 2^5, 2^6, 2^7, 2^8$$

In [5]:
for i in range(1,9):
    print(2**i )


2
4
8
16
32
64
128
256


#### Question 6

**Write a Python program that allows the user to enter any integer value, and displays the value of 2 raised to that power. Your program should function as shown below.**

What power of two? 10

Two to the power of 10 is 1024

In [6]:
a = int(input("ENTER NO:\t"))
print(2**a)

8


#### Question 7

**Write a python program that prompt the user to enter a list of numbers and returns the index of the smallest element in a list of integers.**

**If the number of occurrence of smallest element is greater than 1, return the smallest index.**

In [9]:
l = eval(input("ENTER LIST:"))
m = min(l)
l.index(m)

    

1

#### Question 8

**Losing Your Head over Chess**

The game of chess is generally believed to have been invented in India in the sixth century for a ruling king by one of his subjects. The king was supposedly very delighted with the game and asked the subject what he wanted in return. The subject, being clever, asked for one grain of wheat on the first square, two grains of wheat on the second square, four grains of wheat on the third square, and so forth, doubling the amount on each next square. The king thought that this was a modest reward for such an invention. However, the total amount of wheat would have been more than 1,000 times the current world production.

**Develop and test a Python program that calculates how much wheat this would be in pounds, using the fact that a grain of wheat weighs approximately $1/7,000$ of a pound.**

#### Question 9

**Write a Python program that prompts the user for two floating-point values and displays the result of the first number divided by the second, in integer only.**

In [10]:
no1 = float(input("Enter No:\t"))
no2 = float(input("Enter No:\t"))
print(int(no1/no2))

2


#### Question 10

**Use NumPy to generate a random number between 0 and 1**

In [19]:
print(np.random.rand())

0.03439366989350867


#### Question 11

**Create an array of 20 linearly spaced points between 0 and 1**

In [12]:
import numpy as np

points = np.linspace(0, 1, 20)
print(points)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


#### Question 12

**Create following array using numpy and siply sum of rows and sum of coloumns** <br>
[[ 1,  2,  3,  4,  5],<br>
 [ 6,  7,  8,  9, 10], <br>
 [11, 12, 13, 14, 15], <br>
 [16, 17, 18, 19, 20], <br>
 [21, 22, 23, 24, 25]]

In [13]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10], 
                  [11, 12, 13, 14, 15], 
                  [16, 17, 18, 19, 20], 
                  [21, 22, 23, 24, 25]])
print(array)

row_sum = array.sum(axis=1)
col_sum = array.sum(axis=0)
print("Row sum:", row_sum)
print("Column sum:", col_sum)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Row sum: [ 15  40  65  90 115]
Column sum: [55 60 65 70 75]


**Evaluate each of the following Python expressions first by hand and then verify using jupyter notebook. Assume any value of $(d1,d2,d3)$** <br>
<b>1.</b>	$(d1 + d2 + d3) / 3$ <br>
<b>2.</b>	$d1 + d2 + (d3 / 3)$<br>
<b>3.</b>	$3 * (d1 + d2) * (d1 - d3)$

In [22]:
d1 = 23
d2 = 2
d3 = 44
print((d1 + d2 + d3) / 3)
print(d1 + d2 + (d3 / 3))
print(3 * (d1 + d2) * (d1 - d3))

23.0
39.666666666666664
-1575


In [3]:
def foo(l):
    a = l[0]
    for i in l:
        if i < a:
            a=i
    return a

print(foo([2,3,5,1,7,6]))

1


In [5]:
n = int(input())
for i in range(0,n+1):
	print("*" * i)


*
**
***
****
*****


In [ ]:
b = int(input())
h = int(input())

for i in range(h):
    for j in range(b):
        print("*", end="")
    if i < h-1:
        print()